spring:
  freemarker:
    request-context-attribute: request
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/springboottest?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 1
      max-open-prepared-statements: 2
      initialSize: 1
      timeBetweenEvictionRunsMillis: 3000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'root' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

sso:
  repeatLogin: true
